# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stargazers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stargazers
  pod 'Moya', '~> 15.0'
  pod 'SDWebImage'

  target 'StargazersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StargazersUITests' do
    # Pods for testing
  end

end
